schemaVersion: 1.2
endpoints:
  - name: neo4j
    displayName: Neo4j Database
    service:
      basePath: /browser
      port: 7474
    type: TCP
    networkVisibilities: 
      - Public
  - name: neo4j-bolt
    displayName: Neo4j Bolt
    service:
      basePath: /
      port: 7687
    type: TCP
    networkVisibilities: 
      - Public